### ISSUE TITLE
 error in pak subprocess

### ISSUE THREAD

**Issue by Cuevman81** [cole-brokamp/PurpleAir#4]
→ Will install 1 package.
→ Will download 1 package with unknown size.
+ PurpleAir   0.1.0 [bld][cmp][dl] (GitHub: a79d507)
ℹ Getting 1 pkg with unknown size
✔ Cached copy of PurpleAir 0.1.0 (source) is the latest build
✔ No downloads needed, all packages are cached
ℹ Building PurpleAir 0.1.0
Error:        
! error in pak subprocess
Caused by error: 
! Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
Type .Last.error to see the more details.
> .Last.error
<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! error in pak subprocess
Caused by error: 
! Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
---
Backtrace:
1. pak::pak("cole-brokamp/PurpleAir")
2. pak::pkg_install(pkg, ...)
3. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(...), …
4. err$throw(res$error)
---
Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("pkg_install_do_plan", asNamespace("pak"))(...)
 3. proposal$install()
 4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
 5. base::withCallingHandlers({ …
 6. pkgdepends:::start_task(state, task)
 7. pkgdepends:::start_task_build(state, task)
 8. pkgdepends:::make_build_process(path, pkg, tmp_dir, lib, vignettes, needscompilation, …
 9. pkgdepends:::withr_with_libpaths(c(tmplib, lib), action = "prefix", pkgbuild::pkgbuild_process$new(path, …
10. base::force(code)
11. pkgbuild::pkgbuild_process$new(path, tmp_dir, binary = binary, …
12. local initialize(...)
13. pkgbuild:::rcb_init(self, private, super, path, dest_path, binary, vignettes, …
14. pkgbuild:::build_setup(path, dest_path, binary, vignettes, manual, clean_doc, …
15. pkgbuild:::build_setup_binary(path, dest_path, args, needs_compilation)
16. pkgbuild::check_build_tools(quiet = TRUE)
17. base::stop("Could not find tools necessary to compile a package\n", …
18. | base::.handleSimpleError(function (e) …
19. global h(simpleError(msg, call))

**Comment by cole-brokamp** [comment]
Hi, might be a problem with `pak`; try to install with `remotes::install_github('cole-brokamp/PurpleAir')`. or package will be available as a binary on CRAN hopefully soon 🤞

**Comment by Cuevman81** [comment]
Awesome, thanks so much for quick reply Cole!

**Comment by cole-brokamp** [comment]
I hope that fixed your issue.  Just found out that it should be on CRAN soon, so it would be easier to install that way.

**Comment by Cuevman81** [comment]
That worked!  Thanks so much.
